added smoketest to pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -87,6 +87,25 @@ jobs:
         vuln-type: 'os,library'
         severity: CRITICAL,HIGH
 
+    - name: Run container for smoke test
+      run: |
+        docker run -d --name arknights-test -p 8000:8000 \
+          ${{ secrets.DOCKERHUB_USERNAME }}/arknights-app:latest
+
+        echo "Waiting for container health..."
+        for i in {1..10}; do
+          STATUS=$(docker inspect --format='{{.State.Health.Status}}' arknights-test)
+          echo "Health status: $STATUS"
+          if [ "$STATUS" = "healthy" ]; then
+            exit 0
+          fi
+          sleep 5
+        done
+
+        echo "Container failed healthcheck"
+        docker logs arknights-test
+        exit 1
+
     - name: Push Docker image
       run: |
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/arknights-app:latest
